### ISSUE TITLE
申请适配 逆水寒台服

### ISSUE THREAD

**Issue by s151081** [nakixii/Magisk_AsoulOpt#10]
包名：com.netease.nshmhmt
thank you

**Comment by s151081** [comment]
![Screenshot_2024-12-17-18-44-05-955_com omarea vtools-edit](https://github.com/user-attachments/assets/1e8a39f9-dd2f-4cd5-86dd-478d53821c06)
![Screenshot_2024-12-17-18-47-41-088_com omarea vtools](https://github.com/user-attachments/assets/159b8fa6-43dd-49c9-b600-fc3273176968)
![Screenshot_2024-12-17-18-48-22-316_com omarea vtools-edit](https://github.com/user-attachments/assets/a9e46756-13b5-4331-bd46-7854e09f8f49)
![Screenshot_2024-12-17-18-50-25-910_com omarea vtools-edit](https://github.com/user-attachments/assets/3a9a2936-41fb-4fe7-b228-94b1ecbbb2bb)

**Comment by nakixii** [comment]
提供游戏对局内线程监视器截图

**Comment by s151081** [comment]
![Screenshot_2024-12-18-07-32-43-968_com omarea vtools-edit](https://github.com/user-attachments/assets/662f6aa4-18a3-4347-bd57-857b37633b5c)
![Screenshot_2024-12-18-07-33-03-033_com omarea vtools-edit](https://github.com/user-attachments/assets/36bac380-9c69-4483-ac7b-2638f842ca1c)
