### ISSUE TITLE
New Game Request

### ISSUE THREAD

**Issue by UsamiRabbit** [nakixii/Magisk_AsoulOpt#16]
游戏名：苍翼混沌效应
包名：com.actgames.bbee

![Screenshot_2024-12-26-18-25-05-80](https://github.com/user-attachments/assets/a74404a0-c62f-4a62-bc1f-10add96be9b9)
![Uploading Screenshot_2024-12-26-18-46-58-85.jpg…]()

**A screenshot of the thread statistics**
No need for long screenshots.

**Comment by UsamiRabbit** [comment]
![Uploading Screenshot_2024-12-26-18-46-58-85.jpg…]()

**Comment by UsamiRabbit** [comment]
![Uploading Screenshot_2024-12-26-19-01-36-63_507096bf411ffee187df405bf527ca60.jpg…]()

**Comment by UsamiRabbit** [comment]
![Screenshot_2024-12-26-19-01-39-35_507096bf411ffee187df405bf527ca60](https://github.com/user-attachments/assets/b5e6f97d-dd35-4bd6-aa41-e90abecf7054)
![Uploading Screenshot_2024-12-26-19-01-44-33_507096bf411ffee187df405bf527ca60.jpg…]()

**Comment by nakixii** [comment]
completely blind
