### ISSUE TITLE
New Game Request

### ISSUE THREAD

**Issue by YZSBXX** [nakixii/Magisk_AsoulOpt#17]
游戏名（the name of game）:坦克世界闪击战（World of Tanks Blitz）
包名（Installation package n
![Screenshot_2024-12-27-23-35-50-45](https://github.com/user-attachments/assets/c9ec8870-ae06-4e22-9392-3b20416fb8ee)
ame）:com.tencent.tmgp.yongyong.tksjsjz
![Screenshot_2024-12-27-23-36-17-29](https://github.com/user-attachments/assets/1f43cbe0-8780-4d7e-b32f-267776ba20e6)

**Comment by YZSBXX** [comment]
包名（Installation package name）:com.tencent.tmgp.yongyong.tksjsjz

**Comment by nakixii** [comment]
invalid
